### ISSUE TITLE
Remove bn.js dependency from @cosmjs/math

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cosmjs#203]
All we do there should be possible to do using BigInt

**Comment by ethanfrey** [comment]
Nice to simplify the dependencies

**Comment by willclarktech** [comment]
I believe this means we have to update the TS target to `es2020`.

**Comment by webmaster128** [comment]
Arg, I don't think we want that. I did not follow BigInt support recently and thought it would be easy to get now. Since we get nothing specific from this change, I'd increase the target carefully.

**Comment by willclarktech** [comment]
@webmaster128 Should we close this or think more about whether we can increase the target?

More context suggesting it's not possible to transpile to ES5 even if we added a Babel step (or whatever) after TS compilation: https://v8.dev/features/bigint#polyfilling-transpiling

**Comment by webmaster128** [comment]
We don't need ES5, but it doesn't seem like our current target es2017 helps. Closing for now as we don't have any real need for this change.

**Comment by turadg** [comment]
How about now? ES2020 should be pretty safe in 2024. It would help with https://github.com/cosmos/cosmjs/issues/904
