### ISSUE TITLE
Fork @iov/tendermint-rpc

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cosmjs#204]
We need @cosmjs/tendermint-rpc here, then remove 0.31 support and add 0.33 support.

**Comment by willclarktech** [comment]
@webmaster128 Do we still want v0.32 support? There were some pretty serious breaking changes in v0.33 which will invalidate some of the cross-version types.

**Comment by webmaster128** [comment]
Good question.

[Cosmos SDK 0.38 started to use Tendermint 0.33](https://github.com/cosmos/cosmos-sdk/blob/v0.38.0/go.mod#L28) and for all pre-0.39 blockchains we cannot decode the Amoni data we get from Tendermint. So I think it is safe to remove support for Tendermint 0.32.

My only concern is that we don't show the multi version support anymore if only 0.33 is supported. But that's okay if we keep the infrastructure in place to support 0.33+ in the future.
