### ISSUE TITLE
Add support for SIGN_MODE_DIRECT

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cosmjs#212]
After #211 we need to create a `SignDoc` and `TxRaw` in order to submit a binary tx to Tendermint.

This can either be tested by using curl to send the tranyaction to Tendermint (https://docs.tendermint.com/master/rpc/) or by doing #204 first

**Comment by willclarktech** [comment]
Tracking issue for Cosmos SDK: https://github.com/cosmos/cosmos-sdk/issues/6213
Tracking PR for Cosmos SDK: https://github.com/cosmos/cosmos-sdk/pull/6614

**Comment by ethanfrey** [comment]
I assume this is unblocked by https://github.com/CosmWasm/cosmjs/pull/342 ?

And the issue https://github.com/cosmos/cosmos-sdk/issues/6213 is majority done (awaiting cleanup in the go code).
