### ISSUE TITLE
Add Uint8Array support in @types/pbkdf2

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cosmjs#219]
In https://github.com/crypto-browserify/pbkdf2/pull/81, Uint8Array support was added to the npm package pbkdf2. Unfortunately we cannot use it yet because the new type is not available in @types/pbkdf2.

So we should create a PR to DefinitelyTyped to generalize the input types for `password` and `salt`.

In theory the types should be the same as in https://nodejs.org/api/crypto.html#crypto_crypto_pbkdf2_password_salt_iterations_keylen_digest_callback and https://nodejs.org/api/crypto.html#crypto_crypto_pbkdf2sync_password_salt_iterations_keylen_digest, but the mapping to TypeScript types might be a bit tricky. As far as I can see, the only relevant input types are `string | Buffer | Uint8Array`.

If this is done, we can remove the Buffers from

```ts
  // convert pbkdf2's calllback interface to Promise interface
  private static async pbkdf2(
    secret: Uint8Array,
    salt: Uint8Array,
    iterations: number,
    keylen: number,
    digest: string,
  ): Promise<Uint8Array> {
    return new Promise<any>((resolve, reject) => {
      // TODO: Patch @types/pbkdf2 to allow Uint8Array as secret and salt argument
      pbkdf2(Buffer.from(secret), Buffer.from(salt), iterations, keylen, digest, (err, derivedKey) => {
        if (err) {
          reject(err);
        } else {
          resolve(new Uint8Array(derivedKey));
        }
      });
    });
  }
```

**Comment by willclarktech** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45933

**Comment by webmaster128** [comment]
PR was merged. I think we can use the new types now.
