### ISSUE TITLE
Start Cosmos SDK 0.39 compatible chain in CI

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cosmjs#242]
In order to test the [upcoming](https://github.com/CosmWasm/cosmjs/issues/237) @cosmjs/sdk39, we need a version of gaia running in the CI.

Examples scripts:
- Gaia 2.0 (current CosmosHub): https://github.com/iov-one/iov-core/tree/master/scripts/cosmoshub
- Wasmd (Gaia fork): https://github.com/CosmWasm/cosmjs/tree/master/scripts/wasmd

This includes 3 things

- [x] Find out which version of gaia is the right one (see e.g. https://github.com/cosmos/gaia/issues/425; there is also an ibc-alpha branch 🤷‍♂️)
- [ ] Get docker images
- [ ] Create start/stop scripts

**Comment by webmaster128** [comment]
The first item in the checkbox is answered by this PR: https://github.com/cosmos/cosmos-sdk/pull/6517 We'll use simapp instead of gaia.

**Comment by ethanfrey** [comment]
It seems there is no CI build yet, but you can do the following:

```
git clone https://github.com/cosmos/cosmos-sdk.git
cd cosmos-sdk
git checkout master
git pull

docker build -t cosmwasm/simapp:latest .
docker push cosmwasm/simapp;latest
```

I have just built and pushed this (with my [accepted pr fixing the bank attributes](https://github.com/cosmos/cosmos-sdk/pull/6558)): https://hub.docker.com/r/cosmwasm/simapp/tags

Note this has no scripts like the wasmd one does, but rather you must call docker from your scripts. eg `docker run -p 26657:26657 -p 26656:26656 -v ~/.simapp:/root/.simapp simapp simd init test-chain`

Note that simapp looks for *both* simcli and simd config in `/root/.simapp`, so you may want to mount them on different dirs. Also, there is a [pending PR to merge them into one simd binary](https://github.com/cosmos/cosmos-sdk/pull/6530)
