### ISSUE TITLE
Define common Wallet interface

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmjs#264]
Figure out a common API to represent local keys, chrome extensions that can sign, or ledger nano. Anything that can sign our transactions for us.

It would be good to talk with @thunnini about his design from Keplr / CosmosJS, he was interested in using this with CosmJS

**Comment by Thunnini** [comment]
The link to CosmosJS's wallet provider interface is https://github.com/chainapsis/cosmosjs/blob/master/src/core/walletProvider.ts#L15. 
It works like this order: frontend request the enabling -> wallet determines whether to allow this access -> frontend can get the user's address from the wallet and request the tx builder config optionally if access was allowed -> wallet asks the user to set up tx config -> frontend makes the tx referring the tx config and requests the signing to wallet -> wallet returns the signature if the user approves -> frontend broadcasts it and show the result to the user.
As far as I know, Metamask added such an enabling process before accessing the user's account to mitigate the vulnerability of privacy. So, I think the enabling process is necessary even though it is not required for the process.
The main difference with Metamask is that when a transaction signature is requested, the Metamask wallet sets the config and then adds the signature and broadcasts the tx directly to the node.
However, even if a stdTx exists in the cosmos-sdk, we can't be sure what kind of transaction structure each chain will have. Therefore, the wallet can't broadcast a transaction directly.
So I decided to leave it to the fronted to create a transaction structure and to broadcast the transaction.
However, there is no problem with this process at the moment.
Since the current cosmosJS wallet interface uses some own interfaces, it is necessary to change these types to the type of cosmJS or to use a primitive type. And, in cosmosJS, it passes the values like chain id and bech32 prefix to wallet through context, so we have to decide how to pass these values to the wallet on cosmJS.

**Comment by ethanfrey** [comment]
Thanks for the fast reply. I do like the interface in general. I think we need to think more on the `Context` object as you mentioned, but the rest makes sense. 

I like the enable step for privacy (not sharing all keys with everyone), and note that this can be a simple "internal setup and `Promise.resolve()`" for the case of `LocalWalletProvider`, so it provides a nice hook that is optional.

I guess we can drop the `getTxBuilderConfig` optional method? I am not sure what exactly it does.

And it seems [`Wallet.sign`](https://github.com/chainapsis/cosmosjs/blob/master/src/core/walletProvider.ts#L116-L132) takes the serialized "signBytes" which have the nonce and accountNumber and chainID already inside. Which means, the signer does not need internet access, and this interface could easily support a ledger app as well :smile:

**Comment by ethanfrey** [comment]
Context has a [lot of values](https://github.com/chainapsis/cosmosjs/blob/master/src/core/context.ts#L22-L33) but I see both the local wallet provider as well as a hypothetical ledger app would not need this. If they are only needed for the communication with the extension, maybe those don't have to be in the wallet interface and can be stored inside the `KeplrProvider` (passed inside the constructor of the provider rather than in every method). Would that make sense to you?

I like the `Key` struct and could see keeping it as is.

Something like this:

```ts
export interface WalletProvider {
  /**
   * Request access to the user's accounts. Wallet can ask the user to approve or deny access. If user deny access, it will throw error.
   */
  enable(): Promise<void>;

  /**
   * Get array of keys that includes bech32 address string, address bytes and public key from wallet if user have approved the access.
   */
  getKeys(): Promise<Key[]>;

  /**
   * Request signature from matched address if user have approved the access.
   */
  sign(
    bech32Address: string,
    message: Uint8Array
  ): Promise<Uint8Array>;
}

export interface Key {
  bech32Address: string;
  address: Uint8Array;
  algo: string;
  pubKey: Uint8Array;
}
```

@webmaster128 what do you think as well?

**Comment by webmaster128** [comment]
Is this interface application internal, or a bridge between a webapp and a browser extension? In the later case, it should rather be defined as JSON messages as this the only communication channel you have.

We did that at IOV: [Out of process RPC interface](https://github.com/iov-one/iov-core/blob/v2.5.0/docs/out-of-process-rpc.md). The major difference is that this was an online signer and here an offline signer is preferred.

**Online vs. offline signer**

An online signer signes and broadcasts transactions, an offline signer sends signatures back to the requersting app. The advantage of an offline signer interface is that is can be used with hardware wallets. The advantage of an online signer is that whatever the user approves is guaranteed to be broadcasted.

Problem with offline signers: a malicious app can let the signer sign transactions with consecutive sequence numbers, show error messages to the user that ask to try again. At the end of the day, the app can broadcast all those valid transactions. A webshop for example can let the user pay 3 or 4 times the same amount.

**Comment by willclarktech** [comment]
Are we clear on the use cases we intend to support? Do we maybe need two different interfaces (online and offline)?

**Comment by ethanfrey** [comment]
Very good point @webmaster128 

I would propose using more or less what was discussed above and renaming it `OfflineSigner`. Then we can open a discussion of an `OnlineSigner` interface.

An `OnlineSigner` will likely need to wrap an `OfflineSigner` (local sw keys, ledger, etc) so I think this is a good way to build and define them.

**Comment by ethanfrey** [comment]
> Is this interface application internal, or a bridge between a webapp and a browser extension? In the later case, it should rather be defined as JSON messages as this the only communication channel you have.

The interface should be agnostic of what it is connecting to. We can expose a `Promise<SignedTx>` and then implement with a function call, or by encoding into JSON and sending a message to an extension. I do not see an advantage to trying to standardize on the JSON/network layer - Lunie and Keplr will use different interfaces - but rather the TypeScript interface exposed to the app.

**Comment by willclarktech** [comment]
How does this look?

```ts
export interface AccountData {
  // bech32-encoded
  address: string;
  algo: string;
  pubKey: Uint8Array;
}

export interface WalletProvider {
  /**
   * Request access to the user's accounts. Wallet should ask the user to approve or deny access. Returns true if granted access or false if denied.
   */
  readonly enable: () => Promise<boolean>;

  /**
   * Get AccountData array from wallet. Rejects if not enabled.
   */
  readonly getKeys: () => Promise<readonly AccountData[]>;

  /**
   * Request signature from whichever key corresponds to provided address. Rejects if not enabled.
   */
  readonly sign: (bech32Address: string, message: Uint8Array) => Promise<Uint8Array>;
}
```

**Comment by ethanfrey** [comment]
Looks good to me.

**Comment by webmaster128** [comment]
I'd just avoid the term "key" for pubkeys, as "key" more often than not refers to private keys. So I siggest `getKeys` -> `getAccounts`

**Comment by willclarktech** [comment]
👍 Updated

**Comment by ethanfrey** [comment]
Looks good. I would just put this interface that make a PR implementing #265

**Comment by Thunnini** [comment]
`getTxBuilderConfig` method is used to delegate the feature of setting tx config such as fees or gas to the wallet. I'd like to highlight that this is purely an **optional** method so if the wallet provider doesn't support `getTxBuilderConfig`, it will pass the `getTxBuilderConfig` step.

The reason for this is because the quality of front-end user experience differs massively from one website to the other (i.e. some websites may not give the users an option to set gas/fees). The ability to set this at the wallet level provides a uniform experience regardless of the website UX/UI.

If a user wants to execute a dex trade during network congestion, they should be able to increase their tx fee to prioritize their transaction (even if the front-end interface may not have been designed to accommodate such situations). Removing the `getTxBuilderConfig` method could leave the users at the mercy of the front-end interface.

While this may sound like an unnecessary step for things like hardware wallets, it does provide a lot of benefits from the user experience side.

**Comment by webmaster128** [comment]
Thank you @Thunnini, this makes a lot of sense.

In https://github.com/chainapsis/cosmosjs/blob/v0.0.3-alpha.3/src/core/walletProvider.ts#L26-L35 the parameters are not connected to the transaction. So [many values of TxBuilderConfig](https://github.com/chainapsis/cosmosjs/blob/v0.0.3-alpha.3/src/core/txBuilder.ts#L6-L29) may be set for one transaction and then are outdated for another transaction. How do you solve this issue?

Also _The wallet provider must verify that it is the same as the tx builder config sent earlier or warn the user before signing_ is hard to get right and protect against parallel signing operations. 

> While this may sound like an unnecessary step for things like hardware wallets, it does provide a lot of benefits from the user experience side.

Oh, this is not unnecessary. Very good.

----------

Given all of this above, I think the tx configuration is better placed in the signing flow. This has the consequence that a different transaction may be signed than the one composed by the app, so we need to send back the updated transaction and the signature. Can this cause problems?

**Comment by Thunnini** [comment]
I couldn't understand your sentence well. But, in the current implementation of Keplr's wallet provider, it makes a random id for each request to distinguish multiple requests being made at the same time.

I would agree that it is difficult for the wallet provider to verify a previous tx builder config. In the test version of Keplr, we use the account number and sequence value to check if the tx matches the tx config stored in Keplr. However, in the live version of Keplr we only have warned the user. This will be an area we will need to look into.

In cosmosJS implementation, if `getTxBuilderConfig` is defined by the wallet provider then it requests `txBuilderConfig`. If `getTxBuilderConfig` is not defined by the wallet, it uses the config suggested by the frontend developer. Then the transaction is created by using the config and requests signing to the wallet provider.

**Comment by webmaster128** [comment]
Thank you for the explanation, @Thunnini. Instead of having two requests that need to be connected, why not integrated it in one:

```ts
interface SignResponse {
  /** The SignDoc that was signed by the user. This allows users to adjust parameters such as gas price or the memo in the signing process. Technically it allows changing everything, including the content of the messages. */
  readonly signedSignBytes: Uint8Array;
  readonly signature: StdStignature;
}

export interface WalletProvider {
  // ...

  /**
   * Request signature from whichever key corresponds to provided bech32-encoded address. Rejects if not enabled.
   */
  readonly sign: (address: string, signBytes: Uint8Array) => Promise<SignResponse>;
}
```

**Comment by ethanfrey** [comment]
@webmaster128 

The one issue here is that the client must be able to parse the signedSignBytes and recreate the original tx that needs to be submitted.

Maybe this is easy? I know you had some discussions on the new protobuf format that struct to sign bytes may be non-reversable operation.

**Comment by ethanfrey** [comment]
I would say we are all basically on agreement of the offlinesigner usecase (where the signer/wallet) doesn't change bytes or submit it and we can implement those (including ledger).

Maybe we can make a new issue to discuss the design of an online signer...

Can it generate fees and gas? (I think yes)

Should it submit the tx or return a signed tx?

What information do we return to the calling app?

**Comment by Thunnini** [comment]
Main problem with the combining txBuilderConfig and signing is that the wallet should handle the tx structure. If tx is stdTx, it is not hard. But, if the tx is not a stdTx but custom tx structure, wallet isn’t able to handle this case because the wallet doesn't know the structure of the custom tx.

**Comment by webmaster128** [comment]
> that struct to sign bytes may be non-reversable operation.

Good catch. I think it can easily be made reversible if needed and we document a very good reason here.

> wallet should handle the tx structure

Okay, good feedback. Can we assume there is only one SignDoc type? Then the wallet sends a `SignDoc` to the signer and gets a (potentially updated) `SignDoc` plus a signature back. 

```ts
interface SignDoc {
  readonly account_number: string;
  readonly chain_id: string;
  readonly fee: StdFee;
  readonly memo: string;
  readonly msgs: readonly Msg[];
  readonly sequence: string;
}

interface SignResponse {
  /** The SignDoc that was signed by the user. This allows users to adjust parameters such as gas price or the memo in the signing process. Technically it allows changing everything, including the content of the messages. */
  readonly signedSignDoc: SignDoc;
  readonly signature: StdStignature;
}

export interface WalletProvider {
  // ...

  /**
   * Request signature from whichever key corresponds to provided bech32-encoded address. Rejects if not enabled.
   */
  readonly sign: (address: string, signDoc: SignDoc) => Promise<SignResponse>;
}
```

The signer implementation has `getSignBytes(signDoc: SignDoc): Uint8Array` internally. The application can then create a transaction from the signdoc.

**Comment by webmaster128** [comment]
@Thunnini do you have an example of an app calling `getTxBuilderConfig`? Or a video showing the UI? I don't understand how to use it. How can the end user adjust the memo or fee if this call does not include the transaction that is signed.
