### ISSUE TITLE
sdk38: add support for more modules

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cosmjs#276]
## TypeScript messages types

Arbitrary messages can be sent as JavaScript objects already, but it would be nice to have TypeScript definitions for the most common ones (see `packages/sdk38/src/msgs.ts`).

Cosmos SDK

- [ ] ~~[auth](https://docs.cosmos.network/master/modules/auth/03_messages.html)~~
- [x] [bank](https://docs.cosmos.network/master/modules/bank/03_messages.html)
- [x] [crisis](https://docs.cosmos.network/master/modules/crisis/02_messages.html)
- [x] [distribution](https://docs.cosmos.network/master/modules/distribution/04_messages.html)
- [x] [evidence](https://docs.cosmos.network/master/modules/evidence/03_messages.html)
- [x] [gov](https://docs.cosmos.network/master/modules/gov/03_messages.html)
- [ ] ~~mint~~
- [ ] ~~params~~
- [x] [slashing](https://docs.cosmos.network/master/modules/slashing/03_messages.html)
- [x] [staking](https://docs.cosmos.network/master/modules/staking/03_messages.html)
- [ ] ~~upgrade~~

External

- [x] wasm

## LCD endpoints

[Common endpoints](https://cosmos.network/rpc)

Base endpoints

- [x] /blocks
- [x] /node_info
- [x] /txs (query, broadcast, encode)

Cosmos SDK modules

- [x] /auth (sequence, balance)
- [x] /bank
- [x] /staking (#288)
- [x] /gov (#292)
- [x] /slashing
- [x] /distribution (#295)
- [x] /minting (#287)
- [x] /supply (#280)

External

- [x] /wasm

**Comment by ethanfrey** [comment]
I think there is not ibc in the launchpad release. So maybe that list can be trimmed down a bit. Otherwise looks good.

It would be good to copy all type definitions, but I don't think they all need extensive unit tests. Bank and staking only. 

Maybe later Gov voting (but this has almost no integration tests even in the sdk as it takes so long to run an election with time periods). Just creating a proposal successfully should be enough there to make sure the proposal types are properly formed

**Comment by willclarktech** [comment]
@ethanfrey All the msg types except for IBC were already merged here: https://github.com/CosmWasm/cosmjs/pull/304 (but with low confidence about accuracy because there are no tests).

**Comment by ethanfrey** [comment]
Thanks @willclarktech 

I would just focus tests on bank, staking, and creating a gov proposal. Those are 90% of the messages used by most people. And if you find some easy-to-test low-hanging-fruit go for it.

**Comment by webmaster128** [comment]
Done

**Comment by ethanfrey** [comment]
Nice :tada:
