### ISSUE TITLE
Drop Cosmos SDK 0.38 support in favour of Launchpad

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cosmjs#306]
Staring with wasmd 0.10, our local test chain will be based on Cosmos SDK 0.39 ([Launchpad](https://blog.cosmos.network/launchpad-a-pre-stargate-stable-version-of-the-cosmos-sdk-e0c58d8c4e24)). This is an LTS version of Cosmos SDK many projects use. We assume a Cosmos SDK 0.38 client will not be needed anymore (please let us know if you are willing to fund Cosmos SDK 0.38 client maintenance).

- [ ] Rename package @cosmjs/sdk38 to @cosmjs/launchpad
- [ ] Upgrade local test chain to wasmd 0.10/Cosmos SDK 0.39
- [ ] Link this intro article in the package description: https://blog.cosmos.network/launchpad-a-pre-stargate-stable-version-of-the-cosmos-sdk-e0c58d8c4e24
- [ ] Release CosmJS 0.22.0
- [ ] Deprecate @cosmjs/sdk38 on npm as unmaintained

**Comment by webmaster128** [comment]
@willclarktech The first 3 points should be unblocked with `v0.10.0-alpha` from https://hub.docker.com/r/cosmwasm/wasmd/tags. This version still contains the CosmWasm 0.9 VM and contract ABI but this should not be a problem for this ticket.

**Comment by Thunnini** [comment]
It seems like there isn't a problem on the later versions of the Cosmos-SDK(0.38, 0.39) but because the Cosmos Hub is running 0.37, there was an issue.

The current code is the right implementation for 0.38, so I am not sure how we should handle the 0.37 version.
