### ISSUE TITLE
`getAccount()` method fails on the latest version of cosmos-sdk

### ISSUE THREAD

**Issue by Thunnini** [CosmWasm/cosmjs#312]
https://github.com/CosmWasm/cosmjs/blob/master/packages/sdk38/src/cosmosclient.ts#L222

In the current implementation, `getAccount()` method expects that the public key is delivered as bech32. I'm not sure which version of the cosmos-sdk the changes were made, but accounts on the newer versions of the SDK return as follows:

```
{"height":"2724145","result":{"type":"cosmos-sdk/Account","value":{"address":"cosmos1ntck6f6534u630q87jpamettes6shwgddag769","coins":[{"denom":"uatom","amount":"489300"}],"public_key":{"type":"tendermint/PubKeySecp256k1","value":"Aqb4yDyanddEzrLjbTzhBsowmh6uC6InWAMRmCISoYt5"},"account_number":"58220","sequence":"6"}}}
```

Thus, bech32 decoding will fail and `getAccount()` method doesn't work.
And, because the above public key type is the same as https://github.com/CosmWasm/cosmjs/blob/master/packages/sdk38/src/types.ts#L39, it is not needed to parse them.

**Comment by ethanfrey** [comment]
Good call. I think this changed from 0.38 to launchpad as well. We are working on #306 and hopefully address this there

**Comment by Thunnini** [comment]
It seems like there isn't a problem on the later versions of the Cosmos-SDK(0.38, 0.39) but because the Cosmos Hub is running 0.37, there was an issue.

The current code is the right implementation for 0.38, so I am not sure how we should handle the 0.37 version.

**Comment by ethanfrey** [comment]
Ah, your point was that this code does not work on 0.37? Or in 0.39?

Also, I know there were some changes exactly in pubkey encoding between 0.38 and 0.39... so maybe the 0.39 and 0.37 are the same. We are dropping 0.38 support in any case.

Maybe you can try this PR: https://github.com/CosmWasm/cosmjs/pull/311 which should work for a 0.39 based chain. (still a bit wip, but bank/auth queries/messages work).

**Comment by ethanfrey** [comment]
Nevermind, trying out the code I see this on our launchpad branch.

https://github.com/cosmos/cosmos-sdk/pull/6749 is the root cause.
We will update launchpad support to include this likely on Monday

**Comment by ethanfrey** [comment]
So, 0.39 and 0.37 have the same encoding, and 0.38 was just some broken version (with bech32 addresses > 90 chars)

**Comment by webmaster128** [comment]
We can have a unified client that is more flexible with the format (to support 0.37-0.39). We just need to know what we need and where we get a test blockchain from.

**Comment by webmaster128** [comment]
In #314 you see a solution to support 0.37-0.39 with one client. I think this make everyone's life easier and only took 2 hours (fixing a bug in Uint64 along the way).
