### ISSUE TITLE
Rename "PostTx" to "BroadcastTx"

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cosmjs#317]
In order to make the codebase more familiar for Cosmos developers, I think we should use the term "broadcast" instead of "post" or "submit". If I understand correctly, this is the primary term for dending a signed transaction to a node.

Thoughts @ethanfrey, @Thunnini, @fadeev?

**Comment by ethanfrey** [comment]
Sounds good. "sign" and "broadcast" are the common terms i see in the cosmos-sdk and tendermint

**Comment by fadeev** [comment]
Yes! "Broadcast" for sending signed transactions to `/txs` endpoint. "Submit" is a useful word for a higher level type of interaction: you submit a form that broadcasts a transaction.
