### ISSUE TITLE
@cosmjs/sdk39 published on npm

### ISSUE THREAD

**Issue by fadeev** [CosmWasm/cosmjs#319]
`sdk39` is already there in `v0.21.1` release, but I don't think it has been published to npm. Don't want to rush it, but when it's ready, can you publish it? 🙂

http://npmjs.com/package/@cosmjs/sdk39

**Comment by webmaster128** [comment]
@cosmjs/sdk39 ([now renamed to @cosmjs/sdk40](https://github.com/CosmWasm/cosmjs/pull/290)) is the stargate client, which is far far (far far) from finished. The package [does not contain much](https://github.com/CosmWasm/cosmjs/blob/v0.21.1/packages/sdk39/src/index.ts) more then a name and a definition of dependencies. For this reason it is [set to private](https://github.com/CosmWasm/cosmjs/blob/v0.21.1/packages/sdk39/package.json#L3).

We're basically blocked by the Tendermint and Cosmos SDK teams finishing the backends. Stargate tickets:
- https://github.com/CosmWasm/cosmjs/issues/272
- https://github.com/CosmWasm/cosmjs/issues?q=is%3Aissue+is%3Aopen+label%3Aprotobuf

If you are looking for the launchpad client, this is the place: https://github.com/CosmWasm/cosmjs/milestone/4

**Comment by fadeev** [comment]
Oh, ok, thanks for the clarification 👍
