### ISSUE TITLE
Remove package demo-staking from this repo

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cosmjs#337]
We should avoid needing to maintain and compile this all the time. Also we don't need the staking contract as part of the wasmd start.

@ethanfrey can we remove this now? Or should we move it to a different place?

**Comment by ethanfrey** [comment]
yes, feel free to remove it. It was a deliverable to Terra to show them how to use cosmjs.

However, they don't seem to use cosmjs nor reference this code. If they care, they can look at the `v0.22.0` version
