### ISSUE TITLE
Add tendermint rpc queries

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmjs#350]
Query the following modules using tendermint rpc. All queries that can be done directly via `key` should be done so (as they can get proofs). We can also add higher-level app-queries when it needs processing by the node. I will use the term `proveXyz` when it is a key query (that can be proven to a header) and `getXyz` when it is an app query (that can never be proven):

- [x] auth
  - [x] `proveAccount` (#361)
- [x] bank
  - [x] `proveBalance` (one denom)
  - [x] `getAllBalances` (all denoms)
- [ ] ibc
  - [x] unverified
  - [ ] verified

**Comment by webmaster128** [comment]
@ethanfrey are those the IBC queries we need? https://github.com/cosmos/cosmos-sdk/blob/master/proto/ibc/channel/query.proto#L10-L39

**Comment by ethanfrey** [comment]
Yes, those are the `unverified` queries we need. Good to start with them (super easy). Can you list them above?

I will hand-code the proven version, but it would be great to have those as reference. So the proven version should give the same data as the grpc version where the perform the same query.

**Comment by webmaster128** [comment]
okay. Do you know why they are not added in an ibc folder as the other modules in https://github.com/cosmos/cosmos-sdk/tree/master/proto/cosmos?

**Comment by ethanfrey** [comment]
> okay. Do you know why they are not added in an ibc folder as the other modules in https://github.com/cosmos/cosmos-sdk/tree/master/proto/cosmos?

They are subfolders as IBC is huge.

Actually we will probably want something from client, connection, and commitment at some point, maybe more.

**Comment by webmaster128** [comment]
Last PR was here: https://github.com/CosmWasm/cosmjs/pull/410. Done
