### ISSUE TITLE
Allow to set bech32 prefix, tokens for faucet on command line

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmjs#364]
Either via cli arguments or via environment variables with defaults.

See https://github.com/CosmWasm/cosmjs/blob/master/packages/faucet/src/constants.ts#L8-L24

For the testnet, I want to set the token to `SHELL`/`ushell` and the bech32 prefix to `coral` but this is not possible with the current binary.

**Comment by ethanfrey** [comment]
Please make this as a patch on 0.22 as a 0.22.1 release.

**Comment by webmaster128** [comment]
Done in the 0.22 branch and released as 0.22.1
