### ISSUE TITLE
Give up display tokens in the faucet

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cosmjs#391]
The faucet is the only place in CosmJS where we still have the BCP token tickers supported (e.g. request SHELL instead of ushell). This causes a lot of effort to get right in the faucet and it also seems to confuse testnet users trying to request the base denom.

What about removing

```ts
export interface BankTokenMeta {
  readonly denom: string;
  /**
   * The token ticker symbol, e.g. ATOM or ETH.
   */
  readonly tickerSymbol: string;
  /**
   * The number of fractional digits the token supports.
   *
   * A quantity is expressed as atomic units. 10^fractionalDigits of those
   * atomic units make up 1 token.
   *
   * E.g. in Ethereum 10^18 wei are 1 ETH and from the quantity 123000000000000000000
   * the last 18 digits are the fractional part and the rest the wole part.
   */
  readonly fractionalDigits: number;
}
```

from the faucet entirely and leave it up to UI applications to convert between the base denom and a display token (where the logic needs to exist anyways for all the other APIs).

So instead of

```sh
JSON=$(jq -n --arg addr $(coral keys show -a fred) '{"ticker":"COSM", "address":$addr}') \
  && curl -X POST --header "Content-Type: application/json" --data "$JSON" https://faucet.coralnet.cosmwasm.com/credit
```

you'd

```sh
JSON=$(jq -n --arg addr $(coral keys show -a fred) '{"denom":"ucosm", "address":$addr}') \
  && curl -X POST --header "Content-Type: application/json" --data "$JSON" https://faucet.coralnet.cosmwasm.com/credit
```

@ethanfrey @orkunkl

**Comment by ethanfrey** [comment]
Yes. Please!

It makes everything simpler and removes one more config variable in both frontend apps and @cosmjs/cli

**Comment by ethanfrey** [comment]
On second thought can we punt this to 0.24?

We have the faucets and tutorials set up on coralnet and I would rather not break them.
I like the idea, but now that we have configurable tokens in env variables, I could also define `ushell=10^0ushell` and this would use the native token.

Faucet always seems a bit fragile and I would like to avoid changes before your vacation

**Comment by webmaster128** [comment]
The deployment API [will change](https://github.com/CosmWasm/cosmjs/pull/399) for sure in 0.23, but I guess this is not the critical part.

What we can do as an intermediate step is accept both the display token and the base token

```json
{"ticker":"COSM", "address":$addr}
```

or

```json
{"denom":"ucosm", "address":$addr}
```

at the same time. This allows us to migrate tutorials slowly.

**Comment by ethanfrey** [comment]
Sounds like a good compromise

**Comment by willclarktech** [comment]
I guess #407 didn't actually close this as it's only the intermediate step.

**Comment by webmaster128** [comment]
Thanks Will. Removing this from the 0.23.0 milestone.

**Comment by webmaster128** [comment]
Since both of our current testsnets use CosmJS 0.22.x, we can finish this now on 0.23 or 0.24.
