### ISSUE TITLE
Update Fee tables to take a global gas price + gas limit per operation

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cosmjs#396]
Right now the fee tables looks like

```ts
const defaultFees: FeeTable = {
  upload: {
    amount: coins(25000, "ucosm"),
    gas: "1000000", // one million
  },
  init: {
    amount: coins(12500, "ucosm"),
    gas: "500000", // 500k
  },
  migrate: {
    amount: coins(5000, "ucosm"),
    gas: "200000", // 200k
  },
  exec: {
    amount: coins(5000, "ucosm"),
    gas: "200000", // 200k
  },
  send: {
    amount: coins(2000, "ucosm"),
    gas: "80000", // 80k
  },
  changeAdmin: {
    amount: coins(2000, "ucosm"),
    gas: "80000", // 80k
  },
};
```

The values are a bit arbitrary and work for testnets where everything is free. Due to the data structure we use, the price per gas differs for every operation.

What we want instead is a single gas price that is then multiplied by the gas limit. Ideally this is implemented by a `Coin` with `Decimal` multiplication.

This is inspired by [buildFeeTable](https://github.com/CosmWasm/cosmwasm-plus/blob/master/contracts/cw20-base/helpers.ts#L66-L84)

**Comment by willclarktech** [comment]
@webmaster128 Should the change affect only the default fees or the custom fees as well?

**Comment by webmaster128** [comment]
@willclarktech this is especially important for custom fees. Right now setting them is a pain.
