### ISSUE TITLE
Upgrade all @ledgerhq/* dependencies to version ^5

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cosmjs#441]
At the moment we have a mix between `@ledgerhq/*` version 5 and version 4 dependencies. Version 4 is pulled in by ledger-cosmos-js. It is unclear if version 4 and 5 are even compatible.

So https://github.com/Zondax/ledger-cosmos-js should get an update to version 5. Unfortunately issues are disabled over there. @jleni can you hear this? Can you enable issues for the repo?

**Comment by webmaster128** [comment]
In https://github.com/CosmWasm/dApps/pull/44 you see how those duplicate dependencies are installed in callers

**Comment by jleni** [comment]
@webmaster128 sorry for the confusion. It is a bit confusing that actual issues are being opened in the cosmos org. https://github.com/cosmos/ledger-cosmos-js/issues

We may eventually restructure that and move everything to Zondax as it is the original repo.

**Comment by jleni** [comment]
I will upgrade the dependencies later today, is that fine?

**Comment by webmaster128** [comment]
Ah, thank you. Yeah it would be nice to use one repo for development and issues, no matter which one. But the repo linked from https://www.npmjs.com/package/ledger-cosmos-js should allow opening tickets.

> I will upgrade the dependencies later today, is that fine?

That would be highly appreciated, thanks!

**Comment by webmaster128** [comment]
Thank you @jleni for the quick update!
