### ISSUE TITLE
Create updated simapp test vectors

### ISSUE THREAD

**Issue by willclarktech** [CosmWasm/cosmjs#451]
@ethanfrey previously created these test vectors using a patched simapp to extract the sign bytes etc. As part of https://github.com/CosmWasm/cosmjs/issues/377 we're updating the simapp version and need to regenerate these test vectors for the latest nightly version, e.g. `nightly-2020-10-07`.

https://github.com/CosmWasm/cosmjs/blob/db1f183/packages/proto-signing/src/signing.spec.ts#L29-L61

**Comment by ethanfrey** [comment]
There is a tagged version now!

`v0.40.0-rc0`

We should use this (and future rcs) instead of `nightly` builds from now on. These will also be the tested version on the various testnets and integration layers.
