### ISSUE TITLE
makeSignDoc is not being imported in the CLI package

### ISSUE THREAD

**Issue by antoineherzog** [CosmWasm/cosmjs#457]
I tried to run the CLI however when I type the command makeSignDoc, I got:

node_modules/@cosmjs/cli/[eval].ts:19:17 - error TS2304: Cannot find name 'makeSignDoc'.

**Comment by JakeHartnell** [comment]
I also came across the other day when trying to use `makeSignDoc` in one of our projects.

**Comment by webmaster128** [comment]
What version are you using? `makeSignDoc` was just created recently as part of the (unreleased) CosmJS 0.23. Current stable (0.22.x) does not have it.

It should be available in `0.23.0-alpha.1`on npm and current master of the repo.

**Comment by webmaster128** [comment]
0.23.0 is released now as the latest stable version. Looking at your thumbs up, I assume the problem is solved. Feel free to re-open if that is not the case.
