### ISSUE TITLE
Add support for subscriptions

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmjs#49]
We should expose some sort of subscription listener to the RestClient and use it in the CosmWasmConnection. In particular, for full bcp-compatibility, we need to implement:

* `watchBlockHeaders`
* `watchAccount`

And `postTx` could be done nicer with a subscription that with a poll.

I believe these are needed for dropping in `CosmWasmConnection` into the iov-wallet

**Comment by webmaster128** [comment]
What would also work is a hybrid, where you use a tendermint socker subscribtion to get notified about new data. When you receive a new transaction, you ignore the amino data and pull via REST.

**Comment by ethanfrey** [comment]
Yes, I like this. I think we did some of this at iov. Just have a stream of "update happened" from the subscription service. And those events trigger a rest call to get the data.

I can look into proper tendermint subscription queries,  but that would also require a second url and connection (maybe optional?)

**Comment by webmaster128** [comment]
For wallet integration we need `watchAccount` and `liveTx`. The first one is easy. The second one can be implemented [like Lisk](https://github.com/iov-one/iov-core/blob/v2.0.2/packages/iov-lisk/src/liskconnection.ts#L382-L414). This is horribly inefficient without min/max height search filters, but those [will be available soon](https://github.com/cosmos/cosmos-sdk/pull/5648).

**Comment by webmaster128** [comment]
Closing since the BCP implementation is moving out of here and subscriptions will get their comeback in a couple of weeks when we successfully communicate with Tendermint.
